½dist: trusty
language: node_js
node_js:
  - "stable"
#cache:
#  directories:
#  - node_modules

before_install:
  - cd exam_2

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  API_KEY:
    secure: "MxcRUcHx/jjp+3pJVCgnb7WjwxlsIx2q4ZL3xZUuA1uOVBfQTb8K7ny/4N4PnH8bvWCIUWyKKgrs54YjgnW8GLbGo8uXpRyZyZ3+xvKtqPD7oaGkw4MXsBVJuNg9f8stlRtOnNOU6OmyGjz2lqmXMGOKdIt/YV3+oNHsfFjLkZCynU4UYKu98gbixBZLovbTHGNv0rkmFn36JDCIRl/brLtUMKkt6Sut/ttmjOr6rbLsX0xc63LjjDKqlw7ZllJ1a0BRquiHYGCYvA5hFFTNNXuOs1SJoesduCgdwTTmwbpHXWIPUxj4r+Io2aZTphRhgPpROHt8yW2Xq2yvuqNf0uZTn554jOiruI9gXvAe/vPAOzIIz3M3GqMm+yL/k03K8i8i3hvCGnp2WIpFh7QngYXORLoY9B5FNmKSfMUxbY1XOIhojvQYloqwWZ56xwwtWkF26KFnPhq2ivJSPd6DjIeF3eOIyK/i2at7q0Cl6MmbjqbnoejRIiyRrSF18QdlXJPPt5HDpSn7yPSnPX4Oqm+w23rxEA/Jz7v1rNfhiYRZPC2FrA95ibCGs0lWHuJSG8ZfTmDjIJOWN3wNlsEF66yf8Os1QqKNK6l+G+2fB/nSi9q1TCgG6ZwlmeNyzwrTzVsNi4EGjA8N/N75qyY7UbbI0vICmO5LIuM71z040nY="
  on:
    branch:
      - master
      - devel
      - exam_2
