dist: trusty
language: node_js
node_js:
  - "stable"
#cache:
#  directories:
#  - node_modules

before_install:
  - cd exam_2

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  API_KEY:
    secure: "LqahiETSbdkvEfHrma3II4IlAdw9qhfeRV8jEkAW1LbmFZ9Mamp3/8e2TEZx9sCoqzMUGwoNRMzHSRHl5c5Az8IPiMaY6jrsVwSS2mlXDjq/dSWt7O5fwp4z40b7fiRf494diRGb5cG0PuUP5KQSQf7JYFbV131Z3dLXMPLQscDNCTtb+y7fyenxZucdRGCz3rY8cdDDZzP9GZG/Apzml5KTKTFXzH5QUzKQMs6fbxEmZiQ6JTZ106z7EljBkdbZzaMB9z7lkuIuqIdpOVWxcrLxFexUO/91PECQvIivSnwhCereoXcvHClq5UcJKrrR+Fh/XfPB3hEmOdgQsNufp2Bl3WALwBAANfG8f6zYRpe9I5JckGHesrvyRytxB6XjppUWSpSTmmWvhfF6Zp3gQ6a1/yxQbJxSCJLFTeEFO+6ieTviIAx9KEAdoFhx77P6w1X/LPw42RLDfR1gYBhn9dF9wek4FsnKvcJ01zInoILdW25uye5f1XnjtkZvxEnTtHMqOuM5TPqr2dDoPqPfUwt5an42OTLB5zcbVNWZaA1IY3oGguDBHjcUEEQs+Uiqsrh1suH3tT4AHTgZ3XFYY3oCWry95kHU2DDH4um/GpXUz4Ri6Cs2BRXy45gSfI/TrOdkQK9EHDjAOBeBkK+olKu0v5ObDZaEKIqPReSB3/E="
  on:
    branch:
      - master
      - devel
      - exam_2
