½dist: trusty
language: node_js
node_js:
  - "stable"
#cache:
#  directories:
#  - node_modules

before_install:
  - cd exam_2

env:
  - api_url='https://translate.yandex.net/api/v1.5/tr.json/translate'

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam_2/build
  api_key: $API_KEY
  on:
    branch:
      - master
      - devel
      - exam_2
