version: "3.6"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"

